### ISSUE TITLE
OneUpdater needs to be removed for Gallery updates

### ISSUE THREAD

**Issue by vitorgalvao** [bjornelvar/alfred_nba_scores#4]
Hello @bjornelvar,

In the latest release you’ve added OneUpdater to the workflow. However, that needs to be removed for the workflow to remain in the Gallery. This is because Alfred handles updates of Gallery workflows itself, thus the workflow must not update itself for methods to not conflict.

**Comment by bjornelvar** [comment]
Thanks for letting me know. Just removed it from the workflow and exported it again. The newest one is in the repository.
